trigger:
- main

pool:
  name: 'Default'

variables:
- group: Github_and_Azure_credentials

steps:
- task: PowerShell@2
  displayName: 'Azure CLI'
  inputs:
    targetType: 'inline'
    script: |
      $username = $(AZURE_USERNAME)
      $password = $(AZURE_PASSWORD)
      az login --username $username --password $password
      az account show
      az webapp deployment slot update --resource-group Team13 --name Team13-Ebook --slot production --package $(System.DefaultWorkingDirectory)/*.jar