trigger:
- main

pool:
  name: 'Default'

variables:
- group: Github_and_Azure_credentials

steps:
- task: PowerShell@2
  displayName: 'Azure CLI'
  inputs:
    targetType: 'inline'
    script: |
      az login --service-principal --username $(AZURE_USERNAME) --password $(AZURE_PASSWORD) --tenant $(AZURE_TENANT_ID)
      az account show
      az webapp update --resource-group Team13 --name Team13-Ebook --package $(System.DefaultWorkingDirectory)/*.jar