trigger:
- main

pool:
  name: 'Default'

variables:
- group: Github_and_Azure_credentials

steps:
- task: PowerShell@2
  displayName: 'Azure CLI'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "AZURE_USERNAME: $(AZURE_USERNAME)"
      Write-Host "AZURE_PASSWORD: $(AZURE_PASSWORD)"