trigger:
- main

variables:
  buildConfiguration: release
  resourceGroupName: 'Team13'
  webAppName: 'Team13-Ebook'
  system.debug: true

pool:
  name: Default
  vmImage: 'windows-latest'

jobs:
- job: build
  steps:
  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deployment'
    inputs:
      ConnectionType: 'AzureRM'
      WebAppName: '$(webAppName)'
      ResourceGroupName: '$(resourceGroupName)'
      Package: '$(System.DefaultWorkingDirectory)/*.jar'