trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: release
  resourceGroupName: 'Team13'
  webAppName: 'Team13-Ebook'

steps:
- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-X'

- task: CopyFiles@2
  displayName: 'Copy JAR file to staging directory'
  inputs:
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deployment'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Your Azure Subscription'
    webappName: '$(webAppName)'
    resourceGroupName: '$(resourceGroupName)'
    package: '$(build.artifactstagingdirectory)/*.jar'