trigger:
- main

variables:
  buildConfiguration: release
  resourceGroupName: 'Team13'
  webAppName: 'Team13-Ebook'
  system.debug: true

pool:
  name: Default
  vmImage: 'ubuntu-latest'

jobs:
- job: build
  steps:
  - task: PowerShell@2
    displayName: 'Install Maven'
    inputs:
      targetType: 'filePath'
      filePath: '.github/install_maven.ps1'
      arguments: '-sourcesDirectory $(build.sourcesdirectory)'
  - task: PowerShell@2
    displayName: 'Maven Build'
    inputs:
      targetType: 'inline'
      script: 'vn clean package -X'
  - task: CopyFiles@2
    displayName: 'Copy JAR file to staging directory'
    inputs:
      Contents: '**/*.jar'
      TargetFolder: '$(build.artifactstagingdirectory)'
  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deployment'
    inputs:
      ConnectionType: 'AzureRM'
      WebAppName: '$(webAppName)'
      ResourceGroupName: '$(resourceGroupName)'
      Package: '$(build.artifactstagingdirectory)/*.jar'