trigger:
- main

pool:
  name: 'Default'

steps:
- task: PowerShell@2
  displayName: 'Azure CLI'
  inputs:
    targetType: 'inline'
    script: 'az account show; az webapp deployment update --resource-group Team13 --name Team13-Ebook --package $(System.DefaultWorkingDirectory)/*.jar'