name: Build and upload JAR app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout


    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: microsoft

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: ebook-1.0.jar
          path: '${{ github.workspace }}/target/*.jar'