# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - Team13-Ebook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: microsoft

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ebook-1.0.jar
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ebook-1.0.jar

      - name: Login to Azure
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            echo "Logging in to Azure..."
            az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }} --verbose
            echo "Login successful"
            az account show --verbose
            echo "Account info:"

      - name: Extract Zip Deploy profile
        run: |
          echo "${{ secrets.AZURE_PUBLISHING_PROFILE }}" | grep -oP '(?s)<publishProfile profileName="Team13-Ebook - Zip Deploy".*?</publishProfile>' > zip-deploy-profile.xml

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Team13-Ebook'
          slot-name: 'Production'
          package: 'ebook-1.0.jar'
          publish-profile: 'zip-deploy-profile.xml'
          clean: true